#version 450
#extension GL_ARB_separate_shader_objects : enable

struct Vertex
{
  vec4 position;
  vec4 color;
  vec4 uv;
  vec4 normal;
};

layout (set = 0, binding = 0) buffer TerrainVertexBuffer { Vertex vertices[]; }
terrainVertexBuffer;

void
main ()
{
  uint gID = gl_GlobalInvocationID.x;
  terrainVertexBuffer.vertices[gID].position = vec4 (0.0f, 0.0f, 0.0f, 0.0f);
  terrainVertexBuffer.vertices[gID].color = vec4 (1.0f, 0.0f, 0.0f, 0.0f);
}