name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      shell: bash
      working-directory: ${{github.workspace}}/build
      # Note the current convention is to use the -S and -B options here to specify source 
      # and build directories, but this is only available with CMake 3.13 and higher.  
      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{github.workspace}}/build
      shell: bash
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C $BUILD_TYPE

    - name: clang-tidy review
      # You may pin to the exact commit or the version.
      # uses: ZedThree/clang-tidy-review@c9691287ad181ee643f84ccf178a6a2c147879f0
      uses: ZedThree/clang-tidy-review@v0.6.0
      with:
        # Authentication token
        token: ${{ github.token }}
        # Directory containing the compile_commands.json file
        build_dir: build/
        # Version of clang-tidy to use; one of 6.0, 7, 8, 9, 10
        clang_tidy_version: 10
        # List of checks
        clang_tidy_checks: -*,performance-*,readability-*,bugprone-*,clang-analyzer-*,cppcoreguidelines-*,mpi-*,misc-*
        # Comma-separated list of files or patterns to include
        include: headers/*.h
        # Comma-separated list of files or patterns to exclude
        exclude: ''
        # Comma-separated list of apt packages to install
        apt_packages: ''
        # Maximum number of comments to post at once
        max_comments: 25
        # 
        pr: ${{ github.event.pull_request.number }}
        # 
        repo: ${{ github.repository }}
